import {useEffect,useRef} from 'react';
import * as THREE from 'three';
import {buildCampus,createAvatar} from '../scene/buildCampus';
import {clampToCampus,movementFromKeys} from '../scene/walk-controls';
import {campusSceneTheme,overviewCamera} from '../scene/scene-theme';
import {birdseyeFocusFor} from '../scene/camera-focus';
import type {Place} from '../data/campus';
export default function CampusScene3D({places,onSelect,selectedPlace,mode='birdseye'}:{places:Place[];onSelect:(p:Place)=>void;selectedPlace?:Place;mode?:'birdseye'|'walk'}){
 const ref=useRef<HTMLDivElement>(null);const focus=selectedPlace?birdseyeFocusFor(selectedPlace):{position:overviewCamera.position,target:overviewCamera.target};
 useEffect(()=>{if(!ref.current)return;const host=ref.current,scene=new THREE.Scene();scene.background=new THREE.Color(campusSceneTheme.sky);scene.fog=new THREE.Fog(campusSceneTheme.fog,78,175);const camera=new THREE.PerspectiveCamera(48,host.clientWidth/host.clientHeight,.1,300);const renderer=new THREE.WebGLRenderer({antialias:true});renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(host.clientWidth,host.clientHeight);host.appendChild(renderer.domElement);buildCampus(scene,places);const avatar=createAvatar();avatar.position.set(0,0,0);scene.add(avatar);camera.position.set(...focus.position);camera.lookAt(...focus.target);const keys=new Set<string>();let walking=mode==='walk',yaw=0,pitch=-.25;const key=(e:KeyboardEvent)=>{if(['w','a','s','d','W','A','S','D','Shift'].includes(e.key)){e.preventDefault();keys.add(e.key.toLowerCase())}};const up=(e:KeyboardEvent)=>keys.delete(e.key.toLowerCase());const move=(e:MouseEvent)=>{if(walking){yaw-=e.movementX*.002;pitch=Math.max(-1.1,Math.min(.5,pitch-e.movementY*.002))}};const start=()=>{walking=true;renderer.domElement.requestPointerLock?.()};renderer.domElement.addEventListener('dblclick',start);renderer.domElement.addEventListener('mousemove',move);addEventListener('keydown',key);addEventListener('keyup',up);const resize=()=>{camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix();renderer.setSize(host.clientWidth,host.clientHeight)};addEventListener('resize',resize);let frame=0;const animate=()=>{frame=requestAnimationFrame(animate);if(walking){const delta=movementFromKeys(keys,yaw,keys.has('shift')?.28:.14);const pos=clampToCampus({x:avatar.position.x+delta.x,z:avatar.position.z+delta.z});avatar.position.x=pos.x;avatar.position.z=pos.z;avatar.rotation.y=yaw;camera.position.set(avatar.position.x+Math.sin(yaw)*5,3.3,avatar.position.z+Math.cos(yaw)*5);camera.rotation.order='YXZ';camera.rotation.y=yaw;camera.rotation.x=pitch}else{camera.position.lerp(new THREE.Vector3(...focus.position),.04);camera.lookAt(...focus.target)}renderer.render(scene,camera)};animate();return()=>{cancelAnimationFrame(frame);removeEventListener('resize',resize);removeEventListener('keydown',key);removeEventListener('keyup',up);renderer.dispose();host.removeChild(renderer.domElement)}},[places,onSelect,focus,mode]);return <div id="scene" className="scene-wrap" ref={ref}><div className="scene-hint">{mode==='walk'?'第三人稱漫遊 · W A S D 移動 · Shift 加速 · Esc 離開':'3D 校園鳥瞰 · 點選目的地查看校舍 · 人物漫遊可自由行走'}</div></div>
}
