import * as THREE from 'three';
import type { Place } from '../data/campus';
import {buildingStyleFor} from '../data/building-style';
import {campusSceneTheme as tone} from './scene-theme';
const mat=(color:number,roughness=.82)=>new THREE.MeshStandardMaterial({color,roughness});
const add=(scene:THREE.Scene,mesh:THREE.Object3D)=>scene.add(mesh);
function school(scene:THREE.Scene,p:Place){const style=buildingStyleFor(p.id);const floors=p.id==='admin'||p.name.includes('大樓')?3:2;const w=p.id==='student-center'?19:12;const d=p.id==='student-center'?11:7.8;const h=floors*2.9;const group=new THREE.Group();group.position.set(p.world[0],0,p.world[1]);const plinth=new THREE.Mesh(new THREE.BoxGeometry(w+.45,.42,d+.45),mat(0x777b72));plinth.position.y=.21;group.add(plinth);const wall=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(style==='concrete-special'?0x929992:tone.building));wall.position.y=h/2+.4;wall.castShadow=wall.receiveShadow=true;wall.userData.placeId=p.id;group.add(wall);const roofColor=style==='white-gray-red-roof'?tone.redRoof:tone.darkRoof;const roof=new THREE.Mesh(new THREE.BoxGeometry(w+.75,.42,d+.78),mat(roofColor,.65));roof.position.y=h+.62;roof.castShadow=true;group.add(roof);const cornice=new THREE.Mesh(new THREE.BoxGeometry(w+.16,.18,d+.15),mat(0xc6c8c0));cornice.position.y=h+.28;group.add(cornice);const windowMat=mat(tone.window,.3);for(let floor=0;floor<floors;floor++){const band=new THREE.Mesh(new THREE.BoxGeometry(w+.03,.12,d+.04),mat(0xb4bab3));band.position.y=1.05+floor*2.9;group.add(band);for(let col=0;col<Math.max(4,Math.round(w/2.05));col++){for(const z of [-d/2-.05,d/2+.05]){const win=new THREE.Mesh(new THREE.BoxGeometry(1.15,.96,.09),windowMat);win.position.set(-w/2+1.1+col*(w-2.1)/(Math.max(4,Math.round(w/2.05))-1),1.85+floor*2.9,z);group.add(win)}}}const entry=new THREE.Mesh(new THREE.BoxGeometry(2.45,2.55,.32),mat(0x315e64));entry.position.set(0,1.67,d/2+.18);group.add(entry);const awning=new THREE.Mesh(new THREE.BoxGeometry(3.6,.18,1.1),mat(roofColor));awning.position.set(0,3.02,d/2+.55);group.add(awning);const pin=new THREE.Mesh(new THREE.CylinderGeometry(.2,.2,1.15,10),mat(0xe7bf71));pin.position.set(p.entrance[0]-p.world[0],.75,p.entrance[1]-p.world[1]);pin.userData.placeId=p.id;group.add(pin);add(scene,group)}
function tree(scene:THREE.Scene,x:number,z:number,scale=1){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.13*scale,.2*scale,1.7*scale,7),mat(0x5d4533));trunk.position.y=.85*scale;const crown=mat(0x28583c);for(const [dx,dy,s] of [[0,2.55,1],[.35,2.28,.72],[-.32,2.22,.65]]){const leaf=new THREE.Mesh(new THREE.IcosahedronGeometry(.9*scale*s,1),crown);leaf.position.set(dx*scale,dy*scale,0);leaf.castShadow=true;g.add(leaf)}g.add(trunk);g.position.set(x,0,z);add(scene,g)}
export function createAvatar(){const avatar=new THREE.Group();avatar.name='tour-avatar';const body=new THREE.Mesh(new THREE.CapsuleGeometry(.38,.9,4,8),mat(0x2e668f));body.position.y=1.05;const head=new THREE.Mesh(new THREE.SphereGeometry(.28,12,8),mat(0xf0b18d));head.position.y=1.8;const hair=new THREE.Mesh(new THREE.SphereGeometry(.29,12,8,0,Math.PI*2,0,Math.PI*.55),mat(0x302621));hair.position.y=1.93;avatar.add(body,head,hair);return avatar}
export function buildCampus(scene:THREE.Scene,places:Place[]){const ground=new THREE.Mesh(new THREE.BoxGeometry(130,.8,96),mat(tone.ground));ground.position.y=-.42;ground.receiveShadow=true;add(scene,ground);for(const [x,z,w,d] of [[8,-25,94,8],[31,7,7,61],[-8,-2,53,5]] as number[][]){const edge=new THREE.Mesh(new THREE.BoxGeometry(w+.35,.045,d+.35),mat(0xbdbbae));edge.position.set(x,.035,z);add(scene,edge);const road=new THREE.Mesh(new THREE.BoxGeometry(w,.1,d),mat(tone.road));road.position.set(x,.07,z);road.receiveShadow=true;add(scene,road)}const field=new THREE.Mesh(new THREE.BoxGeometry(58,.15,30),mat(tone.field));field.position.set(-35,.1,19);add(scene,field);const track=new THREE.Mesh(new THREE.RingGeometry(16,21,96),mat(tone.track,.65));track.rotation.x=-Math.PI/2;track.scale.set(1.45,.75,1);track.position.set(-35,.2,19);add(scene,track);const court=new THREE.Mesh(new THREE.BoxGeometry(23,.12,14),mat(0x4d8190));court.position.set(18,.1,29);add(scene,court);places.filter(p=>!['main-gate','track','breezeway','basketball','parking'].includes(p.id)).forEach(p=>school(scene,p));for(let i=0;i<62;i++)tree(scene,-60+(i%11)*12,-40+Math.floor(i/11)*17,.78+(i%4)*.12);for(let i=0;i<8;i++){const hill=new THREE.Mesh(new THREE.IcosahedronGeometry(18+(i%3)*6,2),mat(i%2?0x315d42:0x3d6b48));hill.scale.y=.5;hill.position.set(-80+i*23,-3,58+(i%2)*8);add(scene,hill)}add(scene,new THREE.HemisphereLight(0xd7e9f4,0x314a2b,2.1));const sun=new THREE.DirectionalLight(tone.sun,3.1);sun.position.set(-36,55,28);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);add(scene,sun);return {ground}}
