import * as THREE from 'three';
import type { Place } from '../data/campus';
import {buildingStyleFor} from '../data/building-style';
const mat=(color:number,roughness=.82)=>new THREE.MeshStandardMaterial({color,roughness});
const add=(scene:THREE.Scene,mesh:THREE.Object3D)=>scene.add(mesh);
function school(scene:THREE.Scene,p:Place,index:number){const style=buildingStyleFor(p.id);const floors=p.id==='admin'?3:p.name.includes('大樓')?3:2;const w=p.id==='student-center'?17:11;const d=p.id==='student-center'?10:7;const h=floors*2.2;const group=new THREE.Group();group.position.set(p.world[0],0,p.world[1]);const wall=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(style==='concrete-special'?0x66706e:0xd8d9d1));wall.position.y=h/2;wall.userData.placeId=p.id;group.add(wall);const roofColor=style==='white-gray-red-roof'?0xb96050:0x38524e;const roof=new THREE.Mesh(new THREE.BoxGeometry(w+.45,.45,d+.45),mat(roofColor,.65));roof.position.y=h+.22;group.add(roof);const windowMat=mat(0x254a58,.35);for(let floor=0;floor<floors;floor++){for(let col=0;col<Math.max(4,Math.round(w/2.1));col++){const win=new THREE.Mesh(new THREE.BoxGeometry(1.05,.8,.08),windowMat);win.position.set(-w/2+1.1+col*1.9,1.35+floor*2.15,d/2+.05);group.add(win)}}const entry=new THREE.Mesh(new THREE.BoxGeometry(2.1,2.5,.25),mat(0x3e676d));entry.position.set(0,1.25,d/2+.14);entry.userData.placeId=p.id;group.add(entry);const pin=new THREE.Mesh(new THREE.CylinderGeometry(.28,.28,1.4,10),mat(0xe7bf71));pin.position.set(p.entrance[0]-p.world[0],.7,p.entrance[1]-p.world[1]);pin.userData.placeId=p.id;group.add(pin);add(scene,group)}
function tree(scene:THREE.Scene,x:number,z:number,scale=1){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.13*scale,.2*scale,1.7*scale,7),mat(0x5d4533));trunk.position.y=.85*scale;const crown=new THREE.Mesh(new THREE.ConeGeometry(.9*scale,2.7*scale,9),mat(0x234d37));crown.position.y=2.4*scale;g.add(trunk,crown);g.position.set(x,0,z);add(scene,g)}
export function createAvatar(){const avatar=new THREE.Group();avatar.name='tour-avatar';const body=new THREE.Mesh(new THREE.CapsuleGeometry(.38,.9,4,8),mat(0x2e668f));body.position.y=1.05;const head=new THREE.Mesh(new THREE.SphereGeometry(.28,12,8),mat(0xf0b18d));head.position.y=1.8;const hair=new THREE.Mesh(new THREE.SphereGeometry(.29,12,8,0,Math.PI*2,0,Math.PI*.55),mat(0x302621));hair.position.y=1.93;avatar.add(body,head,hair);return avatar}
export function buildCampus(scene:THREE.Scene,places:Place[]){const ground=new THREE.Mesh(new THREE.BoxGeometry(116,1,82),mat(0x587c45));ground.position.y=-.5;add(scene,ground);const roadMat=mat(0x59605d);for(const [x,z,w,d] of [[8,-25,88,8],[31,7,7,55],[-8,-2,48,5]] as number[][]){const road=new THREE.Mesh(new THREE.BoxGeometry(w,.12,d),roadMat);road.position.set(x,.08,z);add(scene,road)}const field=new THREE.Mesh(new THREE.BoxGeometry(58,.15,30),mat(0x709d3f));field.position.set(-35,.1,19);add(scene,field);const track=new THREE.Mesh(new THREE.RingGeometry(16,21,80),mat(0xad493e,.65));track.rotation.x=-Math.PI/2;track.scale.set(1.45,.75,1);track.position.set(-35,.2,19);add(scene,track);const court=new THREE.Mesh(new THREE.BoxGeometry(21,.2,12),mat(0x4a7f93));court.position.set(18,.2,29);add(scene,court);places.filter(p=>!['main-gate','track','breezeway'].includes(p.id)).forEach(school.bind(null,scene));for(let i=0;i<36;i++)tree(scene,-54+(i%9)*13.3,-37+Math.floor(i/9)*25,i%3===0?1.3:1);const hill=new THREE.Mesh(new THREE.SphereGeometry(70,28,16,0,Math.PI*2,0,Math.PI*.45),mat(0x234433));hill.position.set(-48,-20,42);add(scene,hill);add(scene,new THREE.HemisphereLight(0xcce9ff,0x31452e,2.4));const sun=new THREE.DirectionalLight(0xfff3d3,2.6);sun.position.set(-25,45,30);sun.castShadow=true;add(scene,sun);return {ground}}
